### ISSUE TITLE
Not compatible with German "Umlauts"

### ISSUE THREAD

**Issue by ThomasLeister** [aaronbieber/hue-client#1]
Hey! 

Thanks for providing this tool! I've tried it a couple of minutes ago and it turned out to work as expected! There's only one issue which could be resolved by renaming my lights: 

hue-client doesn't seem to be compatible to German "Umlauts" such as Ä, Ö Ü and more. Is there any chance this can be fixed easily?

**Comment by aaronbieber** [comment]
Thanks for the report, Thomas. Unfortunately I'm not maintaining this tool due to constraints on my time, but Python 3 should be using Unicode strings by default. I'd first check and see if you're using a Python 3.x interpreter in your environment.

If that doesn't solve the problem, more information (error messages, attempts to debug, etc.) might help another contributor solve the issue for you. I will at least add utf-8 encoding annotations to the source files in case that helps Python to behave.

**Comment by ThomasLeister** [comment]
Hi! Yes, Python 3 should fix the problem. But I assume there's some work to be done on the source code until it is compatible with Python3 :-)

> Unfortunately I'm not maintaining this tool due to constraints on my time

That's okay. I can understand. Maybe if there is some spare time, I can dig into it and maybe provide a patch for Python3 / Unicode support. I'm a Python beginner but maybe that is a good opportunity to do some practising.

**Comment by aaronbieber** [comment]
This should be fixed now since #3 was merged.
